import fs from "fs";

export function generateCorrectionCode() {
  const UF_MAP: Record<number, string> = {
    11: "RO", 12: "AC", 13: "AM", 14: "RR", 15: "PA", 16: "AP", 17: "TO",
    21: "MA", 22: "PI", 23: "CE", 24: "RN", 25: "PB", 26: "PE", 27: "AL", 28: "SE", 29: "BA",
    31: "MG", 32: "ES", 33: "RJ", 35: "SP",
    41: "PR", 42: "SC", 43: "RS",
    50: "MS", 51: "MT", 52: "GO", 53: "DF"
  };

  const rawText = fs.readFileSync("public/municipios.json", "utf-8").replace(/^\uFEFF/, "");
  const mun = JSON.parse(rawText);
  
  const officialCitiesByState: Record<string, { norm: string, original: string }[]> = {};
  for (const m of mun) {
    const uf = UF_MAP[m.codigo_uf];
    if (uf) {
      if (!officialCitiesByState[uf]) officialCitiesByState[uf] = [];
      const norm = m.nome.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim();
      officialCitiesByState[uf].push({ norm, original: m.nome });
    }
  }

  let code = `
// AUTOGENERATED CORRECTION DATA
function levenshteinDistance(a: string, b: string): number {
  if (a.length === 0) return b.length;
  if (b.length === 0) return a.length;
  const matrix = [];
  for (let i = 0; i <= b.length; i++) matrix[i] = [i];
  for (let j = 0; j <= a.length; j++) matrix[0][j] = j;
  for (let i = 1; i <= b.length; i++) {
    for (let j = 1; j <= a.length; j++) {
      if (b.charAt(i - 1) == a.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1];
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1,
          Math.min(matrix[i][j - 1] + 1, matrix[i - 1][j] + 1)
        );
      }
    }
  }
  return matrix[b.length][a.length];
}

const OFFICIAL_CITIES: Record<string, { norm: string, original: string }[]> = ${JSON.stringify(officialCitiesByState)};

export function autoCorrectCity(rawCity: string, uf: string): { city: string, uf: string } {
  if (!rawCity || !uf) return { city: rawCity, uf };
  
  const normTyped = rawCity.toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").trim();
  
  if (OFFICIAL_CITIES[uf]) {
    const exactMatch = OFFICIAL_CITIES[uf].find(o => o.norm === normTyped);
    if (exactMatch) return { city: exactMatch.original, uf };
    
    // Check spelling
    let bestMatch = null;
    let minDistance = 999;
    for (const off of OFFICIAL_CITIES[uf]) {
      const dist = levenshteinDistance(normTyped, off.norm);
      if (dist < minDistance) {
        minDistance = dist;
        bestMatch = off;
      }
    }
    const allowedDistance = normTyped.length > 8 ? 3 : (normTyped.length > 5 ? 2 : 1);
    if (bestMatch && minDistance <= allowedDistance) {
      return { city: bestMatch.original, uf };
    }
  }
  
  // If not found in current UF, check other states to see if it belongs there
  for (const testUf of Object.keys(OFFICIAL_CITIES)) {
    const match = OFFICIAL_CITIES[testUf].find(o => o.norm === normTyped);
    if (match) return { city: match.original, uf: testUf };
  }
  
  // Hardcoded generic fallbacks for huge offenders
  if (normTyped === "sao paulo" || normTyped === "s paulo" || normTyped === "spo" || normTyped === "s. paulo") {
    return { city: "São Paulo", uf: "SP" };
  }
  
  // Title case fallback if no match
  const titleCased = rawCity.toLowerCase().split(' ').map(word => {
    if (["de", "da", "do", "das", "dos", "e"].includes(word)) return word;
    return word.charAt(0).toUpperCase() + word.slice(1);
  }).join(' ');
  
  return { city: titleCased, uf };
}
`;
  fs.writeFileSync("cityCorrector.ts", code);
  console.log("Wrote cityCorrector.ts");
}

generateCorrectionCode();
